src/app/globals.css
src/app/layout.tsx
src/app/page.tsx
src/components/EventCountdownBanner/GridBackground/index.tsx
src/components/EventCountdownBanner/index.tsx
src/components/Header/index.tsx

- グリッド背景の実装
- カウントダウン以外のUIを実装（ロゴ、日時と場所、見出し）
- #144BDB をグローバルのプライマリーカラーに設定
- グリッドの透過の度合いを画面サイズごとに調整（他のUI実装後に調整します）
- カウントダウンコンポーネントの修正
https://www.figma.com/design/JKCppXvTVKtFGRa6hNYXBz/Web%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=1-1494&node-type=frame&t=0QuLqtfzuABXHjnE-0

グリッド背景付きのメインビジュアルを実装

---

src/app/wip/page.tsx
src/components/ui/header.tsx

- ヘッダーコンポーネントの作成
- wipページの作成
- フッターコンポーネントをwipページに移動
- 間のmainの要素ができたら移動させる
- tailwind.config.tsを使いたかったのでtsuyuni/20250101からブランチを切っています

ヘッダーコンポーネントの作成

---

src/app/page.tsx
src/components/ApplyToProposal/index.tsx

issue: https://github.com/tskaigi/tskaigi2025-web-site/issues/31
- プロポーザル募集のコンポーネントを作成
- セクション下の飾りのスタイル調整が上手くできていません 🙇 （できなかった）
- 全体的なクラスの付け方が良さそうか
- cursol に聞きつつやったのと、本職じゃないので、自身がないです
- figma の 開発者モードを使ってpixel などを合わせているので、問題ないはずですが、px 合ってそうかも見ていただけると幸いです

プロポーザル募集のcompoennt を作成

---

src/app/wip/page.tsx
src/components/ApplyToProposalSection/index.tsx
src/components/Footer/index.tsx
src/components/MissionSection/index.tsx
src/components/VenueInformation/index.tsx
tailwind.config.ts

- wipページにマップとプロポーザル募集のコンポーネント追加
- 軽微なスタイル修正
- footerのリンク追加
スクショだとheaderの一がなぜかおかしくなってますが、普段は大丈夫だと思います。
| SP | TAB | PC |
|--------|--------|--------|
| ![localhost_3000_wip (4)](https://github.com/user-attachments/assets/809064a3-8519-4f7d-9e9c-f16dd3eda60a) | ![localhost_3000_wip (5)](https://github.com/user-attachments/assets/eaab560b-4a96-4723-b819-3148ec9fc765) | ![localhost_3000_wip (6)](https://github.com/user-attachments/assets/da9e5129-c347-4d37-a5ae-3271aae9af8b)|

wipページにマップとプロポーザル募集のコンポーネント追加

---

src/components/ApplyToProposalSection/index.tsx

- プロポーザル募集の文言と、遷移先をプログラムチームから共有いただいたため、反映しました
（間違えてdevelop で直接作業してしまったので、revert して、branch を切って作業しました）

プロポーザル募集の文言修正と、遷移先の修正

---

src/app/wip/page.tsx
src/components/HeroSectionWithMotion/index.tsx

fix: ヒーローセクションのアスペクト比を変更し、オーバーフローを隠すスタイルを追加

---

src/app/sponsors/page.tsx
src/app/wip/layout.tsx
src/app/wip/page.tsx
src/app/wip/sponsors/[id]/page.tsx
src/app/wip/sponsors/layout.tsx
src/app/wip/sponsors/page.tsx
src/components/sponsors/RoleBadge/index.tsx
src/constants/sponsorList.ts
src/utils/getSponsor.ts

以下の内容を対応しました。
- スポンサー詳細ページの作成（wipのみ）
- スポンサー一覧ページとスポンサー詳細ページのレイアウトを共通化（改善の余地ありそう...）
- コンポーネント名の修正
- https://github.com/tskaigi/tskaigi2025-web-site/pull/121#discussion_r1981429283
以下の内容は対応していません。
- OGPの作成
- wipではないスポンサー詳細ページ
- `/code-of-conduct` にページを追加
- 事前チェックはないので本番用のページに追加
- ページへの動線は別 PR で作成
| PC | Tablet | SP |
| --- | --- | --- |
| ![pc](https://github.com/user-attachments/assets/916fdfdf-f008-4dc4-a752-52dc150fe2ad) | ![tablet](https://github.com/user-attachments/assets/5015d9a0-81b4-4745-9049-f30d5dfd17ed) | ![sp](https://github.com/user-attachments/assets/27e8bffb-1f58-4fa5-af40-b8e305395be3) |
- `/wip/sponsors/XXXX`の`XXXX`の部分

feat: スポンサー詳細ページの作成

---

src/app/sponsors/page.tsx
src/app/wip/sponsors/page.tsx
src/components/sponsors/Company/index.tsx

以下の内容を対応しました。
- WIPの場合、スポンサー一覧ページの企業ロゴを押下時にスポンサー詳細ページへ遷移できるようにする
- WIPではない場合、スポンサー一覧ページの企業ロゴは押下できないようにする
以下の内容は対応していません。
- OGPの作成
- wipではないスポンサー詳細ページ

スポンサー一覧ページからスポンサー詳細ページへ遷移できるようにする

---

src/app/wip/page.tsx
src/components/BuyTicketSection/index.tsx

3/23 のチケット購入フォームオープンに合わせてトップページに反映するための component を作成
フィードバックをもらうために、一旦wip に反映したいです。（文言や、スタイルなど）

feat: チケット購入セクションの作成

---

src/app/page.tsx
src/app/wip/page.tsx
src/components/BuyTicketSection/index.tsx
src/components/MissionSection/index.tsx
src/components/ui/sectionGradation.tsx

3/23 のチケット購入フォームオープンに合わせてトップページに反映するための component を作成
フィードバックをもらうために、一旦wip に反映したいです。
文言などはこちらでやりとりしています
https://tskaigi.slack.com/archives/C0601SMHQAK/p1742354313754079
デザインはこちら: https://www.figma.com/design/JKCppXvTVKtFGRa6hNYXBz/Web%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3?node-id=1362-2360&m=dev

チケット購入セクションをwip に反映

---

src/app/page.tsx
src/app/wip/page.tsx
src/components/BuyTicketSection/index.tsx
src/components/MissionSection/index.tsx
src/components/ui/sectionGradation.tsx

- ホバー時の色を black-100 に変更
- トップページにチケット購入セクションを追加
- wip でも wipじゃなくても firstSection が固定されたので、isFirstSection の分岐を削除
wip に反映したものを 会場チケットチームに 確認いただいています
https://tskaigi.slack.com/archives/C0601SMHQAK/p1742695360632059?thread_ts=1742354313.754079&cid=C0601SMHQAK

トップページにチケット購入セクションを追加 

---

src/constants/sponsorList.ts

GMO Flatt Security株式会社様のスポンサーサービスの名称を修正
- `src/constants/sponsorList.ts`のスポンサーサービス名を以下のように修正
- "Shisho Cloud - 自動脆弱性診断" → "Shisho Cloud byGMO - 自動脆弱性診断"
- "KENRO - セキュアコーディング研修" → "KENRO byGMO - セキュアコーディング研修"
- スポンサー一覧ページ
http://localhost:3001/sponsors
|PC|SMT|
|:-:|:-:|
|<img width="980" alt="スクリーンショット 2025-03-24 14 29 17" src="https://github.com/user-attachments/assets/1de2af02-2256-4b56-8d34-a0cccd3bd8aa" />|<img width="364" alt="スクリーンショット 2025-03-24 14 45 36" src="https://github.com/user-attachments/assets/944c9928-93b9-4066-aa3f-518413c5eefd" />|
- スポンサー詳細ページ
http://localhost:3001/wip/sponsors/gmo-flatt-security
|PC|SMT|
|:-:|:-:|
|<img width="1500" alt="スクリーンショット 2025-03-24 16 47 57" src="https://github.com/user-attachments/assets/ed23930f-948f-44b8-93c9-b426795b8b24" />|<img …

[WIP] fix: スポンサーからの修正依頼 - リンクタイトル修正

---

src/app/sponsors/layout.tsx
src/app/wip/sponsors/layout.tsx

大きい画面での表示の際に、フッターの下に余白ができないようメインコンテンツのサイズを調整しました。

スポンサー詳細ページ 高さ調整

---

src/app/talks/[id]/page.tsx
src/constants/talkList.ts

- トーク詳細ページの一部デザインを実装
- 登壇者情報の表示
- 各トーク内容のデータ作成
| pc | tablet | sp |
| --- | --- | --- |
|![pc](https://github.com/user-attachments/assets/642e35f1-23b8-4828-a1d0-487843c51bfc)|![tablet](https://github.com/user-attachments/assets/df5c4f54-e367-47ab-98d2-40c999632235)|![sp](https://github.com/user-attachments/assets/08eecac1-5f30-41b2-9507-a511512f7251)|

feat: トーク詳細ページの一部を実装

---

src/components/BuyTicketSection/index.tsx

現地参加チケットの完売表示を追加し、スタイルを調整しました。
- 地参加チケット完売のお知らせメッセージを追加
- 現地参加チケットボタンをグレー表示に変更
- オンライン参加チケットボタンのスタイルを調整

現地参加チケット完売表示の追加

---

src/app/wip/talks/[id]/page.tsx

- metadata に description を追加
- OGP 画像の alt をトークタイトルに設定
- webkit で登壇者のアイコンが潰れる問題の対応

fix: トーク詳細ページの改善

---

src/app/talks/[username]/page.tsx

Tablet 以上のサイズのときにプロフィールの分量が多い場合にアイコンが小さくなってしまっていた

fix: 登壇者のアイコンサイズを調整

---

src/app/talks/[username]/page.tsx

画像が横長の場合も楕円にならないように修正
もともと意図通り表示されていた画像もそのまま表示される

fix: 登壇者画像が横長の場合に対応

---

src/components/SideEvent/index.tsx
src/constants/sideEventList.ts

- 5/9時点で確定したサイドイベント情報を追加
- 「公募枠あり」のタグがいくつか抜けているものがあったので追加（スプシ記載漏れでした:bow:）
- サムネイル画像にリンクを貼りました

サイドイベント情報を追加

---

src/app/talks/page.tsx

タイムテーブルにて、2日目（2025/05/24）はDay2タブがデフォルトで開くようにしました。
- 2025/05/10に以下を確認
- `http://localhost:3000/talks` にアクセスすると、**Day1**のタイムテーブルが表示されること
- `http://localhost:3000/talks?day=1` にアクセスすると、Day1のタイムテーブルが表示されること
- `http://localhost:3000/talks?day=2` にアクセスすると、Day2のタイムテーブルが表示されること
- システム設定にて日付を2025/05/24に変更して以下を確認
- `http://localhost:3000/talks` にアクセスすると、**Day2**のタイムテーブルが表示されること
- `http://localhost:3000/talks?day=1` にアクセスすると、Day1のタイムテーブルが表示されること
- `http://localhost:3000/talks?day=2` にアクセスすると、Day2のタイムテーブルが表示されること

feat: タイムテーブルにて、2日目はDay2タブがデフォルトで開く

---

src/components/talks/CommonTrackWrapper/index.tsx
src/components/talks/LtWrapper/index.tsx
src/components/talks/SessionWrapper/index.tsx

- 休憩のセクションの背景色をグレーに
- トーク一覧に登壇者の画像追加
- トークタイトルをホバーした時のスタイル追加
- close #291
- close #293 
- LTのラベルは別で対応します
- リンクをホバーした時はテキストの色が青になるようにしています
- https://tskaigi.slack.com/archives/C062J30MAG6/p1746848162142519

タイムテーブルのスタイル修正

---

src/components/Header/index.tsx
src/components/OnTheDaySection/Notes/Caution/index.tsx
src/components/OnTheDaySection/UrgentAnnouncement/index.tsx
src/components/OnTheDaySection/index.tsx

以下の内容を対応しました。
- ヘッダーのお問い合わせ導線を削除（不要になったため）
- 緊急のお知らせ枠をアクセシブルに変更
- 緊急のお知らせ枠をコメントアウト

feat: 緊急のお知らせ枠の修正

---

src/hooks/useTimetable.ts

タイムテーブルの最初の枠の前にページにアクセス済みの場合、リロードしないと現在時刻用のタイムスロットUIにならない。
5/23か5/24にアクセスしていればリロードしなくても現在時刻用のタイムスロットUIとなるように修正。
https://github.com/user-attachments/assets/41337562-41e3-40b4-98b1-46a5b577f9cc

fix: 現在時刻のタイムスロットだけUIを変える件の改善

---

src/app/talks/[username]/page.tsx

トーク詳細ページにトーク情報の文字情報を追加
