tskaigi/tskaigi2025-web-site

src/components/CountdownTimer/index.tsx
src/components/CountdownTimer/useCountdownTimer.ts

LP用のカウントダウンコンポーネントを作成しました！
色やフォントはデザイナーのFigmaみて調整します

feat: 🎸 add CountdownTimer

---

src/app/page.tsx
src/components/SeekingSponsorsSection/index.tsx

feat: 🎸 add SeekingSponsorsSection

---

src/app/layout.tsx
tailwind.config.ts

style: 💄 with outfit font

---

src/app/layout.tsx

- metadataのdescriptionを適切な日本語に修正

fix: metadata description

---

src/app/page.tsx
src/components/SeekingSponsorsSection/BrowserMockup/index.tsx
src/components/SeekingSponsorsSection/index.tsx
src/components/ui/card.tsx
src/components/ui/input.tsx

スポンサー募集セクションを実装

---

src/app/layout.tsx

- サイト公開に向けてrobotsをindex, followに変更

fix: サイト公開に向けてindex, followに変更

---

src/components/SeekingSponsorsSection/index.tsx

スポンサーの 1 次募集が終了したのでメッセージを変更します.

Change message for recruitment of sponsors

---

src/app/globals.css
src/app/page.tsx
src/app/wip/page.tsx
tailwind.config.ts

- https://github.com/tskaigi/tskaigi2025-web-site/pull/35/filesを参考に、ティザーサイト用のcssの設定やtailwindの設定を元に戻す
- 最初はtailwindのクラスにティザー用のprefixをつけようと思ったが、コードないに置かれているclass名を置換するのが難しそうだったので、そのまま戻したが問題ないか
- ティザーサイトにフッターは必要か

feat: ティザーサイト用のカラーパレットを追加

---

src/components/VenueInformation/index.tsx

issue: https://github.com/tskaigi/tskaigi2025-web-site/issues/32
- 会場へのアクセス情報を表すcomponentを作成した
注意: background が白だと padding がわかりづらいと思うので、一旦青にしてからテストしています

feat: 会場へのアクセス情報を表すcomponent を作成した

---

src/components/ApplyToProposalSection/index.tsx

- プログラムチームに見てもらって、文言を削る判断をしたので修正を反映した
やりとり: https://tskaigi.slack.com/archives/C0624UBP3JT/p1738069010809309

プロポーザル募集の文言調整

---

src/components/ApplyToProposalSection/index.tsx
src/components/Header/index.tsx
src/components/MissionSection/index.tsx
src/components/VenueInformation/index.tsx

[猪野さんにいただいた指摘点](https://tskaigi.slack.com/archives/C062A7FST1V/p1738160452558959?thread_ts=1738063133.364329&cid=C062A7FST1V)を修正したPRです
> ありがとうございます！ここ押さえると印象がパキッとしそうなところのみピックアップします
ヘッダー下シャドウの色や広がり方をFigmaとそろえる
マップ部分の白背景のborder-radiusをFigmaとそろえる
プロポーザル募集の白地部分のpaddingをFigmaと揃える
特に上paddingの空きが気になりました
プライマリボタン(申し込み)のフォントサイズを大きくする
あとは余裕があればなるべくFigmaと合わせていただくで大丈夫だと思います！
| SP | TAB | PC |
|--------|--------|--------|
|![localhost_3000_wip (7)](https://github.com/user-attachments/assets/153189dc-925e-45b7-b4c0-c15bbf566f3d)|![localhost_3000_wip (8)](https://github.com/user-attachments/assets/41f3df2f-e477-4f43-8fd4-e642aa88dccd) | ![localhost_3000_wip (10)](https://github.com/user-attachments/assets/819cd58b-69fe-4dbf-ab26-c85b0183a779)|

fix: 猪野さんにいただいた指摘点の修正

---

src/app/page.tsx

feat(minor): 🎸 トップページを差し替え

---

src/constants/sponsorList.ts

https://tskaigi.slack.com/archives/C062J2VFWG6/p1738750613525589?thread_ts=1738652481.923559&cid=C062J2VFWG6

Change logo link of SPACEMARKET

---

src/constants/sponsorList.ts

確認取れたので公開する.
https://tskaigi.slack.com/archives/C08AV7C6A4E/p1738753977037879?thread_ts=1738753532.540179&cid=C08AV7C6A4E

Publish SPACEMARKET logo

---

src/constants/sponsorList.ts

カミナシさん、公開OK取れました！
https://tskaigi.slack.com/archives/C08BQFVDQ6L/p1738902287264519?thread_ts=1738899372.304019&cid=C08BQFVDQ6L

publish_kaminashi_logo

---

src/components/Header/index.tsx

ヘッダーに表示するスポンサーリンクを作成
コメントアウトしているためまだ非表示

feat: ヘッダーのスポンサーリンク作成

---

src/components/Footer/index.tsx

feat: フッターのスポンサーリンク作成

---

src/app/page.tsx

以下の内容を本番ページに追加。
https://github.com/tskaigi/tskaigi2025-web-site/pull/102

feat: トーク&LT審査員, コアスタッフセクションを本番ページに追加

---

package.json
pnpm-lock.yaml
src/components/Header/index.tsx
src/components/ui/sheet.tsx

- スマホビューの場合はヘッダーのメニュをドロワー形式にする
- リンクに行動規範を追加
| PC | Tablet |
| --- | --- |
|![screenshot 2025-03-13 0 24 35](https://github.com/user-attachments/assets/4a2fb841-b78f-46e8-9c0a-3af94cf391f8)|![screenshot 2025-03-13 0 24 51](https://github.com/user-attachments/assets/bceef0ca-0e74-4e9b-a278-f03910a3adba)|
https://github.com/user-attachments/assets/faa4a346-0a7f-4ccd-a4a5-5d3577056870

feat: ヘッダーのレスポンシブ対応

---

src/constants/sponsorList.ts

- ロゴ確認が不要なスポンサー様の詳細ページを公開する（isTenantChecked=trueに変更）

feat: ロゴ確認が不要なスポンサー様は詳細ページを公開する

---

src/constants/sponsorList.ts

スポンサー修正リクエスト対応

---

src/app/wip/talks/layout.tsx
src/app/wip/talks/page.tsx
src/components/talks/EventDateTab/index.tsx
src/components/talks/TrackToggle/index.tsx
src/constants/talkList.ts

【本番リリース可】タイムテーブルのコンポーネント実装

---

src/constants/sponsorList.ts

- 株式会社スペースマーケット
- フォルシア株式会社
- 株式会社TOKIUM
- 株式会社ドワンゴ
- 株式会社メドレー
- 株式会社Linc'well
- 株式会社カミナシ
- 株式会社サイバーエージェント
- KINTOテクノロジーズ株式会社
- AVITA株式会社

feat: 🎸 チェック済みのテナントを公開

---

src/app/sponsors/layout.tsx
src/app/wip/sponsors/layout.tsx

This reverts commit f8b5cca0ad7fcb301a9bb02712b9ec26e771ee29.

スポンサー詳細ページ 高さ調整

---

.gitignore
src/app/talks/layout.tsx
src/app/talks/page.tsx
src/app/wip/talks/page.tsx
src/components/Footer/index.tsx
src/components/Header/index.tsx
src/components/talks/CommonTrackWrapper/index.tsx
src/components/talks/Day1TimeTable/index.tsx
src/components/talks/Day2TimeTable/index.tsx
src/components/talks/GridWrapper/index.tsx
src/constants/talkList.ts

タイムテーブルページを公開

---

src/components/SponsorsBoardSection/SponsorsBoardItem/index.tsx
src/components/SponsorsBoardSection/index.tsx
src/constants/studentSupportSponsorList.ts

学生支援スポンサー 追加

---

src/components/PersonalSponsorsSection/index.tsx
src/constants/personalSponsorList.ts

画像リンクの修正 && 画像がない人は取り急ぎ真っ白で出す

---

src/app/talks/[username]/page.tsx
src/components/talks/LtWrapper/index.tsx
src/components/talks/SessionWrapper/index.tsx

- タイムテーブル画面からトーク詳細へのリンク追加
- usernameがまだない人にはリンクを追加しない

feat: タイムテーブル画面からトーク詳細へのリンク追加

---

src/constants/sideEventList.ts

サイドイベントのスポンサー名修正

---

src/app/talks/[username]/page.tsx

[fix] word-break

---

src/constants/sideEventList.ts

スタメン様のサイドイベントを追加しました！
https://tskaigi.slack.com/archives/C062J30MAG6/p1747059342040019?thread_ts=1746818276.368189&cid=C062J30MAG6

feat: サイドイベントを追加する

---

src/constants/talkList.ts

Toshiki Itaiさんのbio修正
https://tskaigi.slack.com/archives/C062J30MAG6/p1747028277315249?thread_ts=1747028059.308719&cid=C062J30MAG6

fix: bioの修正

---

src/constants/sideEventList.ts

feat: add new side event

---

src/constants/sponsorList.ts

ジョブボードのURLを修正

---

src/components/Header/index.tsx

close #314 
https://github.com/user-attachments/assets/6365276e-f849-42e2-a448-dbddb1c1ef1e

fix: 画面遷移時にドロワーメニューを閉じる

---

package.json
pnpm-lock.yaml
src/components/talks/CommonTrackWrapper/index.tsx
src/components/talks/Day1TimeTable/index.tsx
src/components/talks/Day2TimeTable/index.tsx
src/components/talks/GridWrapper/index.tsx
src/hooks/useTimetable.ts
src/tests/timetable.spec.tsx
tsconfig.json
vitest.config.mts
vitest.setup.mts

close #289 
現在のセッションにスクロールできるボタンを実装しました！
- SP モードのときのみ表示される
- カンファレンスの開催中のみ表示される
- 現在実施中のセッションを表示しているときは隠れる
システム日付を `2025/5/23 14:30` くらいに設定したときの動き
https://github.com/user-attachments/assets/93e4655d-0c74-4019-94a6-1710678f1fd6
- vitest browser mode による日付をモックしたテスト
- システム日付を変更して動作確認

feat: 現在のセッションにスクロールするボタンの実装

---

src/constants/staffList.ts

fix: スタッフのURL修正

---

src/app/survey/page.tsx

#339 
- 既存のApplyToProposalSectionのコンポーネント参考に追加

アンケートフォーム用ページの追加

---

src/components/talks/CommonTrackWrapper/index.tsx
src/components/talks/GridWrapper/index.tsx
src/constants/talkList.ts
src/tests/timetable.spec.tsx

https://github.com/user-attachments/assets/d5c4a738-55cb-4cf9-9680-26b244b7bc4a

fix: タイムテーブルの挙動と情報を修正

---

src/constants/talkList.ts

TSKaigiに参加することを機にXのアカウントを作成したので、それを追加しました。
開発環境を立てて、Xのリンクが追加されたこととリンク先が正しいことを確認しています。

k8oのxIdを追加

---

src/constants/talkList.ts

アイスクリスタル株式会社の社名を正式表記に修正
